<?php

namespace App\Http\Requests\Admin;

use Illuminate\Foundation\Http\FormRequest;
use Illuminate\Validation\Rule;

class HomepageBuilderRequest extends FormRequest
{
    private const SECTION_TYPES = [
        'hero',
        'features',
        'tools_showcase',
        'how_it_works',
        'pricing',
        'testimonials',
        'faq',
        'stats_bar',
        'cta_banner',
        'latest_posts',
        'newsletter',
        'integrations',
        'richtext',
        'image_carousel',
        'ad_slot',
        'announcement',
        'custom_html',
        'template_grid',
        'all_tools',
    ];

    public function authorize(): bool
    {
        return auth('admin')->check();
    }

    public function rules(): array
    {
        return [
            'sections' => ['required', 'array'],
            'sections.*.id' => ['required', 'string', 'max:80'],
            'sections.*.type' => ['required', 'string', Rule::in(self::SECTION_TYPES)],
            'sections.*.enabled' => ['required', 'boolean'],
            'sections.*.core' => ['required', 'boolean'],
            'sections.*.config' => ['required', 'array'],
            'sections.*.config.headline' => ['nullable', 'string', 'max:300'],
            'sections.*.config.subheadline' => ['nullable', 'string', 'max:500'],
            'sections.*.config.title' => ['nullable', 'string', 'max:300'],
            'sections.*.config.subtitle' => ['nullable', 'string', 'max:500'],
            'sections.*.config.heading' => ['nullable', 'string', 'max:300'],
            'sections.*.config.subheading' => ['nullable', 'string', 'max:500'],
            'sections.*.config.icon' => ['nullable', 'string', 'max:100'],
            'sections.*.config.primary_cta_text' => ['nullable', 'string', 'max:100'],
            'sections.*.config.primary_cta_link' => ['nullable', 'string', 'max:500'],
            'sections.*.config.primary_cta_icon' => ['nullable', 'string', 'max:100'],
            'sections.*.config.primary_cta_icon_position' => ['nullable', 'string', 'max:20'],
            'sections.*.config.secondary_cta_text' => ['nullable', 'string', 'max:100'],
            'sections.*.config.secondary_cta_link' => ['nullable', 'string', 'max:500'],
            'sections.*.config.secondary_cta_icon' => ['nullable', 'string', 'max:100'],
            'sections.*.config.secondary_cta_icon_position' => ['nullable', 'string', 'max:20'],
            'sections.*.config.primary_text' => ['nullable', 'string', 'max:100'],
            'sections.*.config.primary_link' => ['nullable', 'string', 'max:500'],
            'sections.*.config.primary_icon' => ['nullable', 'string', 'max:100'],
            'sections.*.config.primary_style' => ['nullable', 'string', 'max:50'],
            'sections.*.config.secondary_text' => ['nullable', 'string', 'max:100'],
            'sections.*.config.secondary_link' => ['nullable', 'string', 'max:500'],
            'sections.*.config.secondary_icon' => ['nullable', 'string', 'max:100'],
            'sections.*.config.secondary_style' => ['nullable', 'string', 'max:50'],
            'sections.*.config.button_text' => ['nullable', 'string', 'max:100'],
            'sections.*.config.button_link' => ['nullable', 'string', 'max:500'],
            'sections.*.config.button_icon' => ['nullable', 'string', 'max:100'],
            'sections.*.config.button_style' => ['nullable', 'string', 'max:50'],
            'sections.*.config.placeholder_text' => ['nullable', 'string', 'max:200'],
            'sections.*.config.privacy_text' => ['nullable', 'string', 'max:300'],
            'sections.*.config.heading_color' => ['nullable', 'string', 'max:50'],
            'sections.*.config.subheading_color' => ['nullable', 'string', 'max:50'],
            'sections.*.config.learn_more_text' => ['nullable', 'string', 'max:100'],
            'sections.*.config.step_layout' => ['nullable', 'string', Rule::in(['cards', 'timeline', 'compact'])],
            'sections.*.config.step_card_style' => ['nullable', 'string', Rule::in(['simple', 'bordered'])],
            'sections.*.config.background_style' => ['nullable', 'string', 'max:50'],
            'sections.*.config.background_image_url' => ['nullable', 'string', 'max:2048'],
            'sections.*.config.width' => ['nullable', 'string', 'max:50'],
            'sections.*.config.access' => ['nullable', 'string', Rule::in(['everyone', 'logged_in', 'pro'])],
            'sections.*.config.visibility' => ['nullable', 'string', Rule::in(['all', 'desktop', 'tablet', 'mobile', 'desktop_tablet', 'tablet_mobile'])],
            'sections.*.config.section_style' => ['nullable', 'string', Rule::in(['default', 'left_border', 'bottom_accent', 'right_border', 'bottom_border'])],
            'sections.*.config.section_anchor' => ['nullable', 'string', 'max:100'],
            'sections.*.config.custom_class' => ['nullable', 'string', 'max:200'],
            'sections.*.config.animation' => ['nullable', 'string', 'max:50'],
            'sections.*.config.overlay_opacity' => ['nullable', 'integer', 'min:0', 'max:100'],
            'sections.*.config.lazy_load_media' => ['nullable', 'boolean'],
            'sections.*.config.card_style' => ['nullable', 'string', Rule::in(['simple', 'bordered', 'image_focus', 'spotlight'])],
            'sections.*.config.feature_vertical_padding' => ['nullable', 'integer', 'min:0', 'max:240'],
            'sections.*.config.section_vertical_padding' => ['nullable', 'integer', 'min:0', 'max:240'],
            'sections.*.config.source' => ['nullable', 'string', Rule::in(['all', 'featured', 'popular', 'recent', 'free', 'paid'])],
            'sections.*.config.featured_only' => ['nullable', 'boolean'],
            'sections.*.config.trust_badge_text' => ['nullable', 'string', 'max:200'],
            'sections.*.config.cta_text' => ['nullable', 'string', 'max:100'],
            'sections.*.config.cta_link' => ['nullable', 'string', 'max:500'],
            'sections.*.config.cta_style' => ['nullable', 'string', 'max:50'],
            'sections.*.config.cta_icon' => ['nullable', 'string', 'max:100'],
            'sections.*.config.content' => ['nullable', 'string', 'max:20000'],
            'sections.*.config.background_type' => ['nullable', 'string', 'max:50'],
            'sections.*.config.background_value' => ['nullable', 'string', 'max:2048'],
            'sections.*.config.layout' => ['nullable', 'string', 'max:50'],
            'sections.*.config.primary_cta_style' => ['nullable', 'string', 'max:50'],
            'sections.*.config.secondary_cta_style' => ['nullable', 'string', 'max:50'],
            'sections.*.config.hero_background_type' => ['nullable', 'string', 'max:50'],
            'sections.*.config.hero_background_url' => ['nullable', 'string', 'max:2048'],
            'sections.*.config.show_hero_gradient_overlay' => ['nullable', 'boolean'],
            'sections.*.config.show_stats_separator' => ['nullable', 'boolean'],
            'sections.*.config.hero_section_height' => ['nullable', 'string', 'max:50'],
            'sections.*.config.hero_vertical_padding' => ['nullable', 'integer', 'min:0', 'max:240'],
            'sections.*.config.hero_heading_size' => ['nullable', 'string', 'max:50'],
            'sections.*.config.hero_heading_color' => ['nullable', 'string', 'max:50'],
            'sections.*.config.hero_subheading_color' => ['nullable', 'string', 'max:50'],
            'sections.*.config.stats_number_color' => ['nullable', 'string', 'max:50'],
            'sections.*.config.stats_label_color' => ['nullable', 'string', 'max:50'],
            'sections.*.config.items' => ['nullable', 'array'],
            'sections.*.config.items.*.icon' => ['nullable', 'string', 'max:50'],
            'sections.*.config.items.*.title' => ['nullable', 'string', 'max:200'],
            'sections.*.config.items.*.description' => ['nullable', 'string', 'max:500'],
            'sections.*.config.items.*.image_url' => ['nullable', 'string', 'max:500'],
            'sections.*.config.items.*.link_url' => ['nullable', 'string', 'max:500'],
            'sections.*.config.items.*.link_open_new_tab' => ['nullable', 'boolean'],
            'sections.*.config.stats' => ['nullable', 'array'],
            'sections.*.config.stats.*.number' => ['nullable', 'string', 'max:20'],
            'sections.*.config.stats.*.label' => ['nullable', 'string', 'max:100'],
            'sections.*.config.template_slug' => ['nullable', 'string', 'max:100'],
            'sections.*.config.zone' => ['nullable', 'string', 'max:100'],
            'sections.*.config.announcement_type' => ['nullable', 'string', 'max:50'],
            'sections.*.config.style' => ['nullable', 'string', 'max:50'],
            'sections.*.config.interval_ms' => ['nullable', 'integer', 'min:1000', 'max:60000'],
            'sections.*.config.max_items' => ['nullable', 'integer', 'min:1', 'max:50'],
            'sections.*.config.show_filter' => ['nullable', 'boolean'],
            'settings' => ['required', 'array'],
            'settings.seo' => ['required', 'array'],
            'settings.seo.meta_title' => ['nullable', 'string', 'max:160'],
            'settings.seo.meta_description' => ['nullable', 'string', 'max:255'],
            'settings.seo.og_image' => ['nullable', 'string', 'max:2048'],
            'settings.scroll_to_top' => ['required', 'array'],
            'settings.scroll_to_top.enabled' => ['required', 'boolean'],
            'settings.scroll_to_top.position' => ['required', 'string', Rule::in(['left', 'right'])],
            'settings.scroll_to_top.show_after_px' => ['required', 'integer', 'min:0', 'max:5000'],
            'settings.chat_widget_embed' => ['nullable', 'string', 'max:20000'],
        ];
    }
}
